// lib/art-fallbacks.ts
// Primary: local AI-generated Madhubani art (generated by npm run generate:art)
// Fallback: Wikimedia Commons images (used until generate:art is run)
export const ART_FALLBACKS = {
  heroLotus: "/art/hero-lotus.png",
  aboutFish: "/art/about-fish.png",
  dividerPeacock: "/art/divider-peacock.png",
  dividerLotusRow: "/art/divider-lotus-row.png",
  skillsBorder: "/art/skills-border.png",
};

// Wikimedia fallbacks (swap in if local files are missing)
export const ART_WIKIMEDIA_FALLBACKS = {
  heroLotus:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Madhubani_painting.jpg/800px-Madhubani_painting.jpg",
  aboutFish:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Madhubani_painting.jpg/800px-Madhubani_painting.jpg",
  dividerPeacock:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Madhubani_painting.jpg/800px-Madhubani_painting.jpg",
  dividerLotusRow:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Madhubani_painting.jpg/800px-Madhubani_painting.jpg",
  skillsBorder:
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Madhubani_painting.jpg/800px-Madhubani_painting.jpg",
};
